server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-consumer-feignOrder

ribbon:
  # 建立连接后从服务器读取到可用资源所用时间
  ReadTimeout: 5000
  # 建立连接所用时间
  ConnectTimeout: 5000

logging:
  level:
    com.yt4code.springcloud.service.PaymentFeignService: debug